Add TTL to web scanner IP locking KV store (#6847)
* Increase resource requests and limits for Jetstream in StatefulSet

* Remove stream-config.yaml

* Add WEB_SCANNER_IPS KV store in init container

* Add WEB_SCANNER_IPS config to dev docker-compose.yaml

* Remove IP cleanup service calls as KV TTL can be used instead

* Remove ip_cleanup.py from Dockerfile as it is no longer needed

diff --git a/k8s/infrastructure/bases/nats/statefulset.yaml b/k8s/infrastructure/bases/nats/statefulset.yaml
--- a/k8s/infrastructure/bases/nats/statefulset.yaml
+++ b/k8s/infrastructure/bases/nats/statefulset.yaml
@@ -32,11 +32,11 @@ spec:
           mountPath: /data/jetstream
         resources:
           requests:
-            memory: "256Mi"
+            memory: "1Gi"
             cpu: "100m"
           limits:
-            memory: "512Mi"
-            cpu: "500m"
+            memory: "4Gi"
+            cpu: "1000m"
         livenessProbe:
           httpGet:
             path: /healthz
@@ -63,10 +63,13 @@ spec:
             until nc -z localhost 4222; do
               sleep 1
             done
+
             # Small additional delay to ensure JetStream is ready
             sleep 2
+
+            # ==================== CREATE/UPDATE STREAM ====================
             echo "[nats-stream-init] Attempting to add SCANS stream..."
-            if nats stream add SCANS --config /stream-config/stream-config.json --server nats://localhost:4222 2>&1; then
+            if nats stream add SCANS --config /stream-config/stream-config.json --server nats://localhost:4222; then
               echo "[nats-stream-init] SCANS stream added successfully."
             else
               echo "[nats-stream-init] Add failed, attempting to edit SCANS stream..."
@@ -77,6 +80,26 @@ spec:
                 exit 1
               fi
             fi
+
+            # ==================== CREATE/UPDATE KV STORE ====================
+
+            echo "[nats-stream-init] Attempting to add WEB_SCANNER_IPS KV bucket..."
+
+            if nats kv add "WEB_SCANNER_IPS" \
+                --ttl="5m"; then
+              echo "[nats-stream-init] WEB_SCANNER_IPS KV bucket added successfully."
+            else
+              echo "[nats-stream-init] Add failed, attempting to edit WEB_SCANNER_IPS KV bucket..."
+
+              if nats kv edit "WEB_SCANNER_IPS" \
+                  --ttl="5m"; then
+                echo "[nats-stream-init] WEB_SCANNER_IPS KV bucket edited successfully."
+              else
+                echo "[nats-stream-init] ERROR: Could not add or edit WEB_SCANNER_IPS KV bucket!"
+                exit 1
+              fi
+            fi
+
             echo "[nats-stream-init] Stream initialization complete."
             exec sleep infinity
         volumeMounts:
